name: Windows FRP Proxy

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set runner password
      shell: bash
      run: |
        whoami
        net user runneradmin ${{ secrets.WINRCK }}

    - name: Download and extract frp
      shell: bash
      run: |
        curl -L -o a.gz https://github.com/fatedier/frp/releases/download/v0.69.0/frp_0.69.0_windows_amd64.zip
        unzip a.gz
        move frp_* frp

    - name: Write frpc config
      shell: bash
      run: |
        cat > frpc.toml <<'EOF'
        serverAddr = "47.109.40.213"
        serverPort = 7000
        auth.token = "${{ secrets.RCK }}"

        [[proxies]]
        name = "github_action_win"
        type = "tcp"
        localIP = "127.0.0.1"
        localPort = 3389
        remotePort = 2232

        [proxies.plugin]
        type = "socks5"
        EOF

    - name: Run frpc
      shell: bash
      run: |
        timeout 59m ./frpc -c frpc.toml
